elBukkit/MagicPlugin

src/main/java/com/elmakers/mine/bukkit/action/builtin/ChangeContextAction.java
- Relative offsets include relative_target_offset and
relative_source_offset. Both adjust offsets relatively to the player. X
is forwards and backwards, y is up and down, z is left and right.
- Ignore Pitch is self explantory and sets the pitch to 0. Useful for
moves that shouldn't move up or down but should move around the yaw.
- Also removed unused imports
=> Added relative offsets and ignorePitch to ChangeContext

src/main/java/com/elmakers/mine/bukkit/wand/Wand.java
This allows creating "uses: 1" wands out of items that normally stack and allows them to stack naturally.
=> Added concept of single use wands that should stack naturally.

src/main/java/com/elmakers/mine/bukkit/action/builtin/InventoryCloseAction.java
This is necessary for creating multi-layered menus.
A simple example is:
```
actions:
cast:
- class: InventoryClose
- class: Delay
delay: 50
- class: SpellShop
```
=> Added InventoryCloseAction.

src/main/java/com/elmakers/mine/bukkit/magic/listener/PlayerController.java, src/main/java/com/elmakers/mine/bukkit/wand/Wand.java
When this option is enabled, when the player drops an item with Q, it will open the leftmost wand in the inventory. Effectively rebinding Q to "activate wand".
Dropping an item while sneaking and dropping an item by dragging will still work and are ignored by this option.
=> Add option to open a wand when dropping an item

src/main/java/com/elmakers/mine/bukkit/spell/BaseSpell.java
Spectator mode enables flight, invisibility, noclip, and disables interacting with basically anything (but doesn't disable the interact event). It also hides your hud entirely. Casting should probably not be allowed.
=> Disable casting in spectator mode.

src/main/java/com/elmakers/mine/bukkit/action/builtin/SpellShopAction.java
I wonder how long this has been broken and how no one else has noticed it >.>
=> SpellShop should be using the base spell's required path =/

src/main/java/com/elmakers/mine/bukkit/action/builtin/ChangeContextAction.java, src/main/java/com/elmakers/mine/bukkit/action/builtin/CustomProjectileAction.java
Added minimum range parameters for custom projectile spells (entities and/or blocks). This is useful if you want a projectile to travel a certain distance before it has an effect, but don't want it to be able to pass through certain things. Default values should have no effect on how spells currently behave.
Also fixed a small bug in the ChangeContextAction parameters.
Example Spell:
```
spear:
icon: ink_sack:1
icon_url: http://textures.minecraft.net/texture/543a93796b389fc710671b62106068619b7673e7bf48a6c77bc4db921d54
category: combat
worth: 100
earns_sp: 6
class: ActionSpell
actions:
cast:
- class: ChangeContext
actions:
- class: CustomProjectile
actions:
- class: Damage
effects:
cast:
-  class: EffectSingle
sound: entity_player_attack_strong
sound_volume: 0.2
location: origin
-  class: …
```
=> CustomProjectileAction Minimum Range Options

src/main/java/com/elmakers/mine/bukkit/action/builtin/ChangeContextAction.java
This is useful if we are working with whatever action and wants it to fire relatively. For example, using velocity on yourself but wanting it to push you backwards or to the side :)
=> Added relative pitch and yaw offsets to ChangeContext

pom.xml
As can see in the (partial) dependency tree below, `Multiverse-core` depends on a logging library that depends on a totally outdated version of `craftbukkit`. This is causing problems for everyone who does not have this library available when building magic. This PR stops maven from including any of `Multiverse-core`'s sub-dependencies effectively working around the issue.
```
[INFO] +- com.onarandombox.multiversecore:Multiverse-Core:jar:2.5:provided
[INFO] |  +- (org.bukkit:bukkit:jar:1.9-R0.1-SNAPSHOT:provided - version managed from 1.7.2-R0.2; omitted for duplicate)
[INFO] |  +- com.dumptruckman.minecraft:Logging:jar:1.0.9:provided
[INFO] |  |  +- org.bukkit:craftbukkit:jar:1.3.2-R0.2-SNAPSHOT:provided
```
=> Do not include outdated transitive dependencies of multiverse

src/main/java/com/elmakers/mine/bukkit/action/builtin/VelocityAction.java
This check makes sure that no NaN value will ever get passed to `Entity#setVelocity` as it can cause clients to be kicked with an invalid position, which will also not let them back on as it is persisted.
=> Sanity check velocity in VelocityAction

src/main/java/com/elmakers/mine/bukkit/action/ActionHandler.java
This lets third party plugins register action classes properly, without the need to resort to full classpaths.
=> Add ActionHandler#registerActionClass for shorter action classes.

src/main/java/com/elmakers/mine/bukkit/action/builtin/ChangeContextAction.java
The param persistCaster will make all relative changes against the caster and not what sourceLocation or targetLocation may be. This is deal for spells that want to do fancier stuff while all in relative to the player.
=> PersistCaster add-on

Magic/src/main/java/com/elmakers/mine/bukkit/action/builtin/BookAction.java
I've implemented the BookAction that Nathan and I discussed over Discord. This supports replacements for custom currency, attribute values, and target names, though I'm not sure about the format. This code *should* work in theory but it is largely untested and is going to need some revisions (it's much better than the original versions haha.)
I'm not entirely happy with how the flow goes between replacing contents, creating the book, and all that so I'm definitely receptive to suggestions there. I'd also like to expand the number of replacements available.
A use-case for this would be for character sheets where the player's attributes, currency, and more could be displayed in a more visually appealing way.
=> Added BookAction

Magic/src/main/resources/defaults/spells/default.yml, Magic/src/main/resources/examples/survival/spells/mine.yml, Magic/src/main/resources/examples/survival/spells/mount.yml
Fix spells/default.yml note block sounds
Should use block_note_block instead of block_note
Fix level 6 mine spell tool parameter
Should use loot5_pickaxe as a tool instead of loot3_pickaxe which is already used in level 5
Fix mount spell cast sound
Should use iron_golem instead of irongolem
=> Fix sounds in spells/default.yml & mount.yml; fix mine|6 tool parameter

Magic/src/main/resources/examples/survival/wands/divinghelmet.yml
With that effect player can see freely, break blocks a bit faster and breath underwater, so we don't need enchantments here
=> Give divinghelmet a conduit power effect

Magic/src/main/resources/examples/survival/messages/spells.yml, Magic/src/main/resources/examples/survival/spells/mob.yml, Magic/src/main/resources/examples/survival/spells/monster.yml, Magic/src/main/resources/examples/survival/spells/railgun.yml, Magic/src/main/resources/examples/survival/spells/shuriken.yml, Magic/src/main/resources/examples/survival/spells/singularity.yml, Magic/src/main/resources/examples/survival/spells/sunstrike.yml, Magic/src/main/resources/examples/survival/spells/tracking.yml
1) Railgun now has 3 levels:
Upgrade increases range and block/entity hit count, decreases cooldown and manacost
2) Slightly reworked mob spell. Now has 3 levels:
Spawns 10/15/20 mobs at each level. Upgrade decreases cooldown and duration, unlocks new mob types.
3) Reworked singularity. Now has 2 levels:
Now simply creates a small black hole at the target. Deals constant damage at the end. Upgrade increases radius, damage and duration.
4) Added tracking level 5:
Aim down and cast to highlight all mobs/players within a 16 block radius.
5) Monster spell now has 3 levels:
Upgrade unlocks new mob types and increases duration.
6) Completely reworked shuriken:
Now uses new ModifyNoDamageTicks action. Upgrade increases projectile's lifetime and hit count.
Very strong spell if been used inside …
=> 1st part of changes/additions to the survival spells

Magic/src/main/resources/examples/survival/messages/spells.yml, Magic/src/main/resources/examples/survival/spells/harden.yml, Magic/src/main/resources/examples/survival/spells/meteor.yml, Magic/src/main/resources/examples/survival/spells/petrify.yml, Magic/src/main/resources/examples/survival/spells/shuriken.yml, Magic/src/main/resources/examples/survival/spells/silence.yml, Magic/src/main/resources/examples/survival/spells/sunstrike.yml, Magic/src/main/resources/examples/survival/spells/workbench.yml
1) Rebalanced silence spell. Now has 3 levels:
Upgrade decreases manacost and cooldown, increases duration.
2) Sunstrike now has 3 levels:
Upgrade increases max damage(10/20/40), decreases delay.
3) Rework shuriken again:
Now uses this strange mechanic to target same entity multiple times.
Tried also ignore_hit_entities, but it causes strange behavior there projectile is "stuck" in the same entity, damaging him multiple times.
4) Rework meteor spell:
Now summons one big meteor, that shoots smaller meteors when flying. Big meteor deals 5x damage and breaks blocks in a 16 block radius.
Has 2 levels. Upgrade increases small meteor count, decreases cooldown.
5) Rebalance harden spell. Now has 5 levels:
Upgrade increases duration. Each level has different block type (stone/stone bricks/smooth …
=> 2nd part of additions/changes to survival spells

Magic/src/main/java/com/elmakers/mine/bukkit/spell/TargetingSpell.java
I needed to make a spell only target people with specific permissions, and so I made this parameter to do this! I thought this would be pretty useful :smile:
=> Create new target_permission parameter for projectile to target

Magic/src/main/java/com/elmakers/mine/bukkit/magic/MagicController.java, Magic/src/main/java/com/elmakers/mine/bukkit/magic/listener/BlockController.java
I just want to point out that this is a completely optional setting which can be configured in config.yml. Also, none of this feature will run on default (the default is allowing it to break), it will have to be specified in the parameter. Basically what this will do is disallow paintings from breaking if you are holding a wand. It can be annoying, and so I decided to add a fix for it!
Example usage:
`can_wands_break_paintings: false`
=> Stop painting break if player is holding wand (optional)

Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicCommandExecutor.java, Magic/src/main/java/com/elmakers/mine/bukkit/utility/MagicLogger.java, MagicAPI/src/main/java/com/elmakers/mine/bukkit/api/event/MagicErrorEvent.java, MagicAPI/src/main/java/com/elmakers/mine/bukkit/api/event/MagicWarningEvent.java
New log API events consist of:
- MagicErrorEvent
- MagicWarningEvent
MagicLogger now stores 50 errors and warnings at max, as well as calls the new API events. Additionally, the code was cleaned up a bit. With the new commands, it uses functions from the MagicLogger to display the logs for easy of use! Please let me know if anything needs to be improved or changed, and I can make the changes. Thank you!
=> Refactor MagicLogger to store warning/errors, create new magic command /magic log (errors|warnings), and create Magic API log events

Magic/src/main/resources/examples/survival/spells/kill.yml
The kill spell deals less damage at higher levels. Specifically, its level one effect has "player_damage: 1000", but then the level two and level three effects have "player_damage:25" and "player_damage:30" in them, and both of those numbers are significantly less than 1000.
This should fix that. 
Also, the Kill spell only deals 30 (up to 40 with max level) damage against entities. I'm not sure if this is a bug or not, so I left it untouched, but it is something to look at.
=> Fixed kill dealing less damage at higher levels

Magic/src/main/resources/defaults/messages/arena.yml
Noticed a few mistakes in the default arena messages when testing during our update to `10.8.8`.
* removed the extra space before `&6hearts`
* changed `$6wins` to `&6wins` so the text appears the correct colour
=> Fix arena default win message mistake

Magic/src/main/java/com/elmakers/mine/bukkit/arena/Arena.java
The order in which arena message placeholders would get replaced was incorrect, causing the `$playerDisplay` and `$playerPath` placeholders to never get parsed correctly. Because `$player`would get replaced first, any occurences of the other two would become `MyCoolUsernameDisplay` and `MyCoolUserNamePath` and would no longer be recognized as the placeholders they were.
Simply replacing `$player` last fixes this.
=> Fix arena message replacement logic

Magic/pom.xml, Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicGiveCommandExecutor.java
Heya! :D
How are you?
A little bit more details:
1) The maven-shade-plugin dependency was 3.3.0-SNAPSHOT which is no longer available so I updated it to 3.3.0.
2) There was a NullPointerException on the mgive command on some versions such as 1.12.2 since the effect type on the 0 index in the potion effect types was null.
=> Fixed missing dependency and NullPointerException 

Magic/src/main/java/com/elmakers/mine/bukkit/action/builtin/AreaOfEffectAction.java, Magic/src/main/java/com/elmakers/mine/bukkit/action/builtin/LineOfEffectAction.java
LineOfEffect provides a new targeting method which target entities along the view direction, all entities in the cylinder(with height=rangeFront-rangeBack, radius=radius) will be targeted. I copied code from AreaOfEffectAction to implement this, and noticed that the process of 'target_count' may need extra review, because I don't really understand it.
Also added a new parameter 'random_choose' for AreaOfEffect and LineOfEffect, allowing the action to choose randomly, instead of calculating scores and select the best.
=> add LineOfEffect, random choose parameter for AreaOfEffect

CompatibilityLib/v1_21_1/src/main/java/com/elmakers/mine/bukkit/utility/platform/v1_21_1/InventoryUtils.java
After 1.21 setProfile changes to accept ResolvableProfile instead of GameProfile, this just adds a wrapper or accepts ResolvableProfile directly.
Fixes #1376
=> Change in parameters for CraftSkull for 1.21

CompatibilityLib/base/src/main/java/com/elmakers/mine/bukkit/utility/platform/base/InventoryUtilsBase.java, CompatibilityLib/common/src/main/java/com/elmakers/mine/bukkit/utility/CompatibilityConstants.java, Magic/src/main/java/com/elmakers/mine/bukkit/magic/MagicController.java
There was a bug in the legacy versions (at least checked on 1.12.2) which wands with a textured skull icon would have bugged to all have the same texture, this happened since the UUID used for the heads was the same.
I fixed it by changing the UUID to be deterministic derived from the URL.
=> Fixed the legacy player heads wands bug that caused them to only have one texture

Magic/src/main/java/com/elmakers/mine/bukkit/magic/command/MagicMapCommandExecutor.java
Before Minecraft 1.13, map IDs were limited to 32768. This is no longer the case. However, Magic still limit the IDs in the `/mmap` command.
This pull request removes the `short` casts around map IDs.
Demonstration below, assuming your server contains more than 32768 map IDs.
**Before:**
1. Run `/mmap load https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/255px-Flag_of_France.svg.png`. A map with id 33645 is loaded.
2. Because of `short` casts, the given map has the ID -31891. So it's invalid and appears blank.
3. Run `/mmap give 33645`. It doesn't work, the ID is considered invalid by Magic.
4. Run `/give @s minecraft:filled_map{map:33645}`. It does work, because vanilla limit no longer exist.
**After:**
1. Run `/mmap load …
=> Fix map IDs casted as shorts

Magic/src/main/resources/defaults/materials/all_leaves.yml, Magic/src/main/resources/defaults/materials/logs.yml, Magic/src/main/resources/defaults/materials/saplings.yml, Magic/src/main/resources/defaults/materials/trees.yml
Added the new Pale Oak logs, leaves, and sapling to the default materials files.
Also, added the mangrove roots and mangrove propagule.
I tested the changes in a local server with the .yaml files added in the config, and it worked.
=> Add pale oak and (rest of) mangrove to materials files

Magic/src/main/java/com/elmakers/mine/bukkit/action/builtin/RectOfEffectAction.java
I was in need of an ability to select targets across a cuboid space, much like the AreaOfEffect action, but in a precise rectangle oriented to the player. I didn't end up getting a clear answer on previous questions on github, nor from the community on the discord server, as such I have spent some time working on this action myself.
This was mainly created for my own purposes, but if you're interested it can be included in the plugin.
It uses a 'min' and 'max' vector parameter to set 2 corners of the targeting box (much like how World edit cuboids are selected), relative to the source location's position and yaw. 
The rest of the targeting it the same as how AreaOfEffect does this. I have tested this action on my own server and this is working as expected, but more specific testing may be …
=> Feature - RectOfEffect action
